### ISSUE TITLE
package is missing entry_points

### ISSUE THREAD

**Issue by aqc-carlodri** [conda-forge/pytest-benchmark-feedstock#15]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

The package is missing the entry_points listed here in the source:

https://github.com/ionelmc/pytest-benchmark/blob/7dace6163c53189f7cf8faf09f669af055f197ae/setup.py#L88-L91

### Installed packages

```shell
n/a
```

### Environment info

```shell
n/a
```

**Comment by astrojuanlu** [comment]
If I understand correctly, this is how we should add them: https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html?highlight=entry#python-entry-points

@aqc-carlodri would you like to send a PR?

**Comment by aqc-carlodri** [comment]
> If I understand correctly, this is how we should add them: https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html?highlight=entry#python-entry-points

yes, exactly

> @aqc-carlodri would you like to send a PR?

I will try to find some time, yes, it should be easy

**Comment by aqc-carlodri** [comment]
@astrojuanlu PR #16 is ready for review & merge
